name: bloc_toolkit
description: "A package that provides a set of tools for efficient and flexible state management using the Bloc pattern."
version: 0.0.1-beta.2
homepage: https://github.com/dadagov125/bloc_toolkit

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  bloc: ^8.0.0
  bloc_concurrency: ^0.2.5
  meta: ^1.3.0

dev_dependencies:
  bloc_test: ^9.0.0
  test: ^1.18.2
  mocktail: ^1.0.4



