name: bloc_toolkit
description: "A new Flutter project."
version: 0.0.1-beta.1
homepage: none
repository: https://github.com/dadagov125/bloc_toolkit

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  bloc: ^8.0.0
  bloc_concurrency: ^0.2.5
  meta: ^1.3.0

dev_dependencies:
  bloc_test: ^9.0.0
  test: ^1.18.2



